// Sign tab: manifest details, ISCC unit selection, CAWG training-mining choices, credentials and
// the timestamp service.

import type { AppInfo, Credentials, Inspection, IsccUnit, SignRequest, SignResult, TrainingEntry, TsaPreset } from "../api";
import { contentSource, embedding } from "../formats";
import { esc, fullStop, isccHtml, splitPath } from "../util";
import { USE_CASES } from "./credentials";

/** Digital source types offered for new manifests (IPTC NewsCodes and C2PA additions). */
const SOURCE_TYPES: { uri: string; label: string }[] = [
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/digitalCapture", label: "Digital capture (camera)" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/computationalCapture", label: "Computational capture" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/negativeFilm", label: "Scanned negative film" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/positiveFilm", label: "Scanned positive film" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/print", label: "Scanned print" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/digitalArt", label: "Digital art" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/digitalCreation", label: "Digital creation" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/screenCapture", label: "Screen capture" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/softwareImage", label: "Software rendered image" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/dataDrivenMedia", label: "Data driven media" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia", label: "Generated by AI (trained algorithmic media)" },
  {
    uri: "http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia",
    label: "Composite with AI generated content",
  },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/algorithmicallyEnhanced", label: "Algorithmically enhanced" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/algorithmicMedia", label: "Algorithmic media (no training)" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/composite", label: "Composite" },
  { uri: "http://cv.iptc.org/newscodes/digitalsourcetype/humanEdits", label: "Human edits" },
  { uri: "http://c2pa.org/digitalsourcetype/empty", label: "Empty (blank canvas)" },
];

const SIGNING_ALGS = ["es256", "es384", "es512", "ps256", "ps384", "ps512", "ed25519"];

interface UnitOption {
  slug: string;
  unit: IsccUnit["unit"];
  title: string;
  desc: string;
}

/** The Content-Code offered for an asset: image, text or audio. */
function contentOption(inspection: Inspection): UnitOption {
  if (inspection.kind === "text") {
    return {
      slug: "text",
      unit: "content",
      title: "Content-Code Text",
      desc: "Similarity hash of the text in reading order. Survives reformatting, re-packaging and metadata edits.",
    };
  }
  if (inspection.kind === "audio") {
    return {
      slug: "audio",
      unit: "content",
      title: "Content-Code Audio",
      desc: `Chromaprint fingerprint of the ${contentSource(inspection)}. Survives re-encoding, format changes and metadata edits.`,
    };
  }
  return {
    slug: "image",
    unit: "content",
    title: "Content-Code Image",
    desc: `Perceptual hash of the ${contentSource(inspection)}. Survives re-encoding, resizing and metadata stripping.`,
  };
}

/** What the Instance-Code will prove after signing (IEP-0020, Source Preservation). */
function afterSigning(inspection: Inspection): string {
  if (inspection.manifest) {
    return "This file already has Content Credentials, which signing replaces, so after signing Data-Code and Instance-Code identify this file, not the signed copy.";
  }
  const e = embedding(inspection);
  if (e.kind === "preserved") {
    return "Signing only inserts the Content Credentials, so it will show that the signed copy without them is this file, byte for byte.";
  }
  return `After signing, Data-Code and Instance-Code identify this file, not the signed copy: ${e.kind === "changed" ? "signing " : ""}${e.why}.`;
}

/** Units offered for an asset, all computed from the file exactly as it is (IEP-0020). */
function unitOptions(inspection: Inspection): UnitOption[] {
  return [
    {
      slug: "meta",
      unit: "meta",
      title: "Meta-Code",
      desc: "Similarity hash of title and description, both stored in the Content Credentials (cawg.metadata). Needs a title.",
    },
    contentOption(inspection),
    {
      slug: "data",
      unit: "data",
      title: "Data-Code",
      desc: "Similarity hash of the file's bytes. Tolerates small byte-level edits, not re-encoding.",
    },
    {
      slug: "instance",
      unit: "instance",
      title: "Instance-Code",
      desc: `Cryptographic hash of the file's bytes, the identity of this exact file. ${afterSigning(inspection)}`,
    },
  ];
}

/** Value of the timestamp select that reveals the URL field. */
const CUSTOM_TSA = "custom";

/** Timestamp choice: on or off, a preset URL or `CUSTOM_TSA`, and the custom URL. */
export interface TimestampChoice {
  on: boolean;
  preset: string;
  custom: string;
}

/** Mutable form state, kept across re-renders so a re-render never loses input. */
export interface SignForm {
  title: string;
  description: string;
  sourceType: string;
  units: Set<string>;
  training: Record<string, TrainingEntry>;
  credentials: Credentials;
  timestamp: TimestampChoice;
  output: string;
  metaPreview: IsccUnit | null;
  /** Why the backend could not compute the Meta-Code preview for a non-empty title. */
  metaError: string | null;
}

/** Placeholder for the Meta-Code preview when there is no code to show. */
export function metaPreviewHint(form: SignForm): string {
  return form.metaError ? `not available: ${form.metaError}` : "enter a title to preview";
}

/** Fresh form state for a newly loaded file; timestamps with the first preset. */
export function newSignForm(inspection: Inspection, presets: TsaPreset[]): SignForm {
  return {
    title: inspection.meta_fields.name,
    description: inspection.meta_fields.description ?? "",
    sourceType: SOURCE_TYPES[0].uri,
    units: new Set(["meta", inspection.kind, "data", "instance"]),
    training: {},
    credentials: { kind: "demo" },
    timestamp: { on: presets.length > 0, preset: presets[0]?.url ?? CUSTOM_TSA, custom: "" },
    output: inspection.suggested_output,
    metaPreview: null,
    metaError: null,
  };
}

/** Problems that keep the form from being signed; empty when it is complete. */
export function signProblems(form: SignForm, inspection: Inspection): string[] {
  const problems: string[] = [];
  if (inspection.sign_block) problems.push(inspection.sign_block);
  if (!form.title.trim()) problems.push("A title is required.");
  if (form.units.size === 0) problems.push("Select at least one ISCC unit.");
  if (form.units.has("meta") && !form.title.trim()) problems.push("The Meta-Code needs a title.");
  for (const [key, entry] of Object.entries(form.training)) {
    if (entry.use === "constrained" && !entry.constraint_info?.trim()) problems.push(`Describe the constraint for ${key}.`);
  }
  if (form.credentials.kind === "custom" && (!form.credentials.cert_path || !form.credentials.key_path))
    problems.push("Choose a certificate and a private key.");
  if (form.timestamp.on && form.timestamp.preset === CUSTOM_TSA && !/^https?:\/\/\S+$/i.test(form.timestamp.custom.trim()))
    problems.push("Enter the timestamp service URL, starting with http:// or https://.");
  const sourceExt = splitPath(inspection.path).ext.toLowerCase();
  if (splitPath(form.output).ext.toLowerCase() !== sourceExt) problems.push(`The output must keep the ${sourceExt} extension.`);
  return problems;
}

/** Set the training-mining choice `use` for `key` (empty clears it); a constraint text is kept only
 * while the choice is "constrained". */
export function setTrainingUse(form: SignForm, key: string, use: string) {
  if (!use) delete form.training[key];
  else form.training[key] = { use, constraint_info: use === "constrained" ? (form.training[key]?.constraint_info ?? "") : undefined };
  if (use !== "constrained" && form.training[key]) delete form.training[key].constraint_info;
}

/** URL of the chosen timestamp service; undefined when timestamps are off. */
function tsaUrl(choice: TimestampChoice): string | undefined {
  if (!choice.on) return undefined;
  return choice.preset === CUSTOM_TSA ? choice.custom.trim() : choice.preset;
}

/** Host of a URL for messages, else the URL itself. */
function hostOf(url: string): string {
  try {
    return new URL(url).host;
  } catch {
    return url;
  }
}

/** Success message after signing, and a note when the timestamp service failed. */
export function signedMessages(result: SignResult): { text: string; note: string | null } {
  const n = result.units.length;
  let text = `Signed and embedded ${n} ISCC unit${n === 1 ? "" : "s"} into ${result.inspection.file_name}.`;
  const ts = result.inspection.manifest?.signature?.timestamp;
  if (result.timestamp.status === "added" && ts) {
    const by = ts.tsa ?? "the timestamp service";
    text +=
      ts.status === "trusted"
        ? ` Timestamp verified by ${by}${fullStop(by)}`
        : ` Timestamped by ${by}, which is not on the C2PA trust list.`;
  }
  const note =
    result.timestamp.status === "failed"
      ? `Signed without a timestamp: ${hostOf(result.timestamp.url)} failed (${result.timestamp.reason}). The signature is valid; only the signing time is not proven. Sign again later to add one.`
      : null;
  return { text, note };
}

/** Build the request the Rust side expects. */
export function toRequest(form: SignForm, inspection: Inspection): SignRequest {
  return {
    source: inspection.path,
    output: form.output,
    title: form.title.trim(),
    description: form.description.trim() || undefined,
    meta: inspection.meta_fields.meta ?? undefined,
    source_type: form.sourceType,
    units: [...form.units],
    training: form.training,
    credentials: form.credentials,
    tsa_url: tsaUrl(form.timestamp),
  };
}

/** Timestamp fieldset: on/off, a preset service or a custom URL. */
function timestampFieldset(choice: TimestampChoice, info: AppInfo | null): string {
  const presets = info?.tsa_presets ?? [];
  const options = presets
    .map((p) => {
      const label = `${p.name} — ${p.trusted ? "on" : "not on"} the C2PA trust list`;
      return `<option value="${esc(p.url)}" ${p.url === choice.preset ? "selected" : ""}>${esc(label)}</option>`;
    })
    .join("");
  const custom = choice.preset === CUSTOM_TSA;
  const off = choice.on ? "" : "disabled";
  return `
      <div class="fieldset">
        <div class="legend">Timestamp <span class="hint mono">RFC 3161 · proves when the file was signed</span></div>
        <label class="radio"><input type="checkbox" name="ts_on" ${choice.on ? "checked" : ""} /><span>Add a timestamp</span></label>
        <div class="field">
          <label for="f-tsa">Timestamp service</label>
          <select id="f-tsa" name="ts_preset" ${off}>
            ${options}<option value="${CUSTOM_TSA}" ${custom ? "selected" : ""}>Custom URL…</option>
          </select>
        </div>
        ${
          custom
            ? `<div class="field">
          <label for="f-tsa-url">Service URL</label>
          <input type="text" class="mono" id="f-tsa-url" name="ts_custom" value="${esc(choice.custom)}" placeholder="https://" ${off} />
        </div>`
            : ""
        }
        <span class="hint">Only a hash of the signature is sent. If the service does not answer within ${info?.tsa_timeout_secs ?? 10} s, the file is signed without a timestamp.</span>
      </div>`;
}

/** Render the sign form. */
export function signTab(form: SignForm, inspection: Inspection, info: AppInfo | null): string {
  const hasManifest = Boolean(inspection.manifest);
  const computed = new Map(inspection.iscc.map((u) => [u.name, u.iscc]));
  const custom = form.credentials.kind === "custom" ? form.credentials : null;

  const unitChecks = unitOptions(inspection)
    .map((o) => {
      const code = o.slug === "meta" ? (form.metaPreview?.iscc ?? null) : (computed.get(o.title) ?? null);
      return `
      <label class="check">
        <input type="checkbox" name="unit" value="${o.slug}" ${form.units.has(o.slug) ? "checked" : ""} />
        <span class="title"><span class="swatch" data-unit="${o.unit}"></span>${esc(o.title)}</span>
        <span class="desc">${esc(o.desc)}</span>
        ${code ? `<span class="code" data-meta-code="${o.slug === "meta" ? "1" : ""}">${isccHtml(code)}</span>` : o.slug === "meta" ? `<span class="code" data-meta-code="1" style="color:var(--muted)">${esc(metaPreviewHint(form))}</span>` : ""}
      </label>`;
    })
    .join("");

  const useRows = USE_CASES.map((u) => {
    const entry = form.training[u.key];
    const current = entry?.use ?? "";
    const seg = [
      ["", "Unset"],
      ["allowed", "Allowed"],
      ["notAllowed", "Not allowed"],
      ["constrained", "Constrained"],
    ]
      .map(([v, l]) => `<button type="button" data-use-key="${u.key}" data-use="${v}" aria-pressed="${current === v}">${l}</button>`)
      .join("");
    const constraint =
      current === "constrained"
        ? `<input type="text" name="constraint:${u.key}" placeholder="Constraint details (required)" value="${esc(entry?.constraint_info ?? "")}" />`
        : "";
    return `
      <div class="usecase">
        <div><div class="label">${esc(u.label)}</div><div class="key">${esc(u.key)}</div></div>
        <div class="segmented">${seg}</div>
        ${constraint}
      </div>`;
  }).join("");

  return `
    <form class="card form" id="sign-form" autocomplete="off">
      <div class="fieldset">
        <div class="legend">Manifest <span class="hint">${hasManifest ? "this file and its Content Credentials become the parent ingredient of a new manifest (c2pa.opened)" : "this file becomes the parent ingredient of a new manifest (c2pa.opened)"}</span></div>
        <div class="field">
          <label for="f-title">Title</label>
          <input type="text" id="f-title" name="title" value="${esc(form.title)}" required />
        </div>
        <div class="field">
          <label for="f-description">Description <span class="hint">(optional, feeds the Meta-Code)</span></label>
          <input type="text" id="f-description" name="description" value="${esc(form.description)}" />
        </div>
        ${
          hasManifest
            ? ""
            : `<div class="field">
          <label for="f-source">How was this ${inspection.kind === "image" ? "image" : "file"} made? <span class="hint">(recorded on the parent ingredient)</span></label>
          <select id="f-source" name="source_type">
            ${SOURCE_TYPES.map((s) => `<option value="${s.uri}" ${s.uri === form.sourceType ? "selected" : ""}>${esc(s.label)}</option>`).join("")}
          </select>
        </div>`
        }
      </div>

      <div class="fieldset">
        <div class="legend">ISCC soft binding <span class="hint mono">c2pa.soft-binding · io.iscc.v0</span></div>
        ${unitChecks}
      </div>

      <div class="fieldset">
        <div class="legend">Training and data mining <span class="hint mono">cawg.training-mining · leave all unset to omit the assertion</span></div>
        <div>${useRows}</div>
      </div>

      <div class="fieldset">
        <div class="legend">Signing credentials</div>
        <label class="radio"><input type="radio" name="cred" value="demo" ${form.credentials.kind === "demo" ? "checked" : ""} /><span>Built-in demo certificate <span class="hint">(c2pa-rs test key, ES256; trusted only inside this app)</span></span></label>
        <label class="radio"><input type="radio" name="cred" value="custom" ${custom ? "checked" : ""} /><span>My own certificate and key</span></label>
        ${
          custom
            ? `
        <div class="field">
          <label>Certificate chain (PEM)</label>
          <div class="row"><input type="text" class="mono" name="cert_path" value="${esc(custom.cert_path)}" readonly placeholder="choose a .pem or .pub file" /><button type="button" class="btn" data-pick="cert_path">Choose</button></div>
        </div>
        <div class="field">
          <label>Private key (PEM)</label>
          <div class="row"><input type="text" class="mono" name="key_path" value="${esc(custom.key_path)}" readonly placeholder="choose a .pem or .key file" /><button type="button" class="btn" data-pick="key_path">Choose</button></div>
        </div>
        <div class="field">
          <label for="f-alg">Signature algorithm</label>
          <select id="f-alg" name="alg">${SIGNING_ALGS.map((a) => `<option value="${a}" ${a === custom.alg ? "selected" : ""}>${a.toUpperCase()}</option>`).join("")}</select>
        </div>`
            : ""
        }
      </div>

      ${timestampFieldset(form.timestamp, info)}

      <div class="fieldset">
        <div class="legend">Output</div>
        <div class="field">
          <label>Signed copy is written to</label>
          <div class="row"><input type="text" class="mono" name="output" value="${esc(form.output)}" readonly /><button type="button" class="btn" data-pick="output">Choose</button></div>
        </div>
      </div>

      ${signActions(inspection)}
    </form>`;
}

/** The submit area: the reason a file cannot be signed in place of the button, or the button
 * with a warning above it when signing does something to the file its owner may not want. */
function signActions(inspection: Inspection): string {
  if (inspection.sign_block) {
    return `<div class="actions"><p class="banner error grow">${esc(inspection.sign_block)}</p></div>`;
  }
  const warning = inspection.sign_warning ? `<p class="banner warn">${esc(inspection.sign_warning)}</p>` : "";
  return `
      ${warning}
      <div class="actions">
        <span class="msg" id="sign-msg"></span>
        <button type="submit" class="btn primary" id="sign-submit">Sign and embed</button>
      </div>`;
}
